# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 15:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collectinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.UUIDField()),
                ('form_name', models.CharField(default='\u672a\u547d\u540d\u8868\u5355', max_length=128)),
                ('create_time', models.DateTimeField()),
                ('edit_time', models.DateTimeField()),
                ('cooperation', models.BinaryField(default=0)),
                ('fill_mode', models.BinaryField(default=0)),
                ('create_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
